[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "publicai-api"
version = "0.1.7"
description = "Official Python client for the Public AI Gateway (platform.publicai.co)."
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
authors = [
  { name = "Public AI", email = "hello@publicai.network" }
]
dependencies = [
    "anyio>=4.13.0",
    "certifi>=2026.2.25",
    "charset-normalizer>=3.4.6",
    "h11>=0.16.0",
    "httpcore>=1.0.9",
    "httpx>=0.28.1",
    "idna>=3.11",
    "requests>=2.33.0",
    "urllib3>=2.6.3"
]
classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Intended Audience :: Developers",
  "Topic :: Software Development :: Libraries",
  "Topic :: Scientific/Engineering :: Artificial Intelligence",
]

[project.urls]
Homepage = "https://platform.publicai.co/docs"
Source = "https://github.com/AakashGnanavelu/publicai-api"

[tool.setuptools]
packages = ["publicai"]

